{% set name = "markdownlint-cli2" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/markdownlint-cli2/-/markdownlint-cli2-{{ version }}.tgz
  sha256: 162969e38018574754f29749fff5e5a7520865dee5f1405553d93fd3f899342c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
    - pnpm-licenses
  run:
    - nodejs
test:
  commands:
    - markdownlint-cli2 test.md

about:
  home: https://github.com/DavidAnson/markdownlint-cli2
  summary: A fast, flexible, configuration-based command-line interface for linting Markdown/CommonMark files with the markdownlint library
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - mahf708
